app: daoscan
service: ui
org: ukstv

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: "daoscan.net"
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: nodejs12.x
  region: "us-east-1"

package:
  include:
    - dist/**

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-domain-manager

functions:
  server:
    handler: functions/server.handle
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
